/*
 * This File is the Primary File in Legora Core Source Code
 * From Here the All Code for Modules, Generators, Projects, Attributes will be in This Project
 * This Project Will be Shared with Website, CLI, and The Desktop Application Will Use This Attributes
 * Return values from Website Server Request and Draw the UI on Desktop, Then Submit the Results to the Generator CLI
 * By Executing The Command Line CLI Arguments for Each Generator in the Project
 *
 * The Project Structure is the Following
 * 1. The Core Source Code is the Generic Source Code for CLI
 * 2. Cli Will Support Commands for All Generators
 * 3. This Core Source Code will be Included as a Dependency in The Website
 * 4. Website is Running on The Server and Will return Everything Required to UI by Api Request
 * 5. Desktop Application Will Execute Command Line With The Filled Arguments
 * 6. CLI Will Start Generating From Generators in Core Library
 * 7. Everything is Generated by Templating Engine to Generate Templates
 * 8. All Core Files is Written in **.mjs to Support Modules Import
 *
 * Project Author: Yazan Tarifi : https://github.com/Yazan98
 * Project Link : https://github.com/Yazan98/Legora
 * Project Website https://legora.me
 *
 */
console.log("Legora index.js Started !!")